server:
  port: 1208
  servlet:
    context-path: /ems
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://39.106.154.90:3306/cmfz
    url: jdbc:mysql://localhost:3306/ems?zeroDateTimeBehavior=convertToNull
    username: root
    password: 1221997
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  type-aliases-package: com.shun.entity
  mapper-locations: classpath:com/shun/mapper/*Mapper.xml
logging:
  level:
    com.shun.dao: debug
